use diesel::Queryable;
use serde::{Deserialize, Serialize};

#[derive(Queryable, Serialize, Deserialize)]
pub struct Card {
    pub id: u32,
    pub card_id: u32,
    pub foil_card_id: u32,
    pub card_set_id: u32,
    pub card_name: String,
    pub card_name_ruby: String,
    pub is_foil: u8,
    pub char_type: u8,
    pub tribe_name: String,
    pub skill: String,
    pub skill_condition: String,
    pub skill_target: String,
    pub skill_option: String,
    pub skill_preprocess: String,
    pub skill_disc: String,
    pub org_skill_disc: String,
    pub evo_skill_disc: String,
    pub org_evo_skill_disc: String,
    pub cost: u8,
    pub atk: u8,
    pub life: u8,
    pub evo_atk: u8,
    pub evo_life: u8,
    pub rarity: u8,
    pub get_red_ether: u32,
    pub use_red_ether: u32,
    pub description: String,
    pub evo_description: String,
    pub cv: String,
    pub copyright: Option<String>,
    pub base_card_id: u32,
    pub normal_card_id: u32,
    pub format_type: u8,
    pub restricted_count: u8,
}
