// @generated automatically by Diesel CLI.

diesel::table! {
    cards (id) {
        id -> Int4,
        card_id -> Int4,
        foil_card_id -> Int4,
        card_set_id -> Int4,
        card_name -> Varchar,
        card_name_ruby -> Nullable<Varchar>,
        is_foil -> Nullable<Int2>,
        char_type -> Nullable<Int2>,
        clan -> Int2,
        tribe_name -> Nullable<Varchar>,
        skill -> Varchar,
        skill_condition -> Varchar,
        skill_target -> Nullable<Varchar>,
        skill_option -> Nullable<Varchar>,
        skill_preprocess -> Nullable<Varchar>,
        skill_disc -> Nullable<Text>,
        org_skill_disc -> Nullable<Text>,
        evo_skill_disc -> Nullable<Text>,
        org_evo_skill_disc -> Nullable<Text>,
        cost -> Int2,
        atk -> Int2,
        life -> Int2,
        evo_atk -> Nullable<Int2>,
        evo_life -> Nullable<Int2>,
        rarity -> Nullable<Int2>,
        get_red_ether -> Nullable<Int4>,
        use_red_ether -> Nullable<Int4>,
        description -> Nullable<Text>,
        evo_description -> Nullable<Text>,
        cv -> Nullable<Varchar>,
        copyright -> Nullable<Varchar>,
        base_card_id -> Int4,
        normal_card_id -> Int4,
        format_type -> Nullable<Int2>,
        restricted_count -> Nullable<Int2>,
    }
}
