-- Your SQL goes here
CREATE TABLE cards (
    id SERIAL PRIMARY KEY,
    card_id INTEGER NOT NULL,
    foil_card_id INTEGER NOT NULL,
    card_set_id INTEGER NOT NULL,
    card_name VARCHAR(255) NOT NULL CHECK(card_name <> ''),
    card_name_ruby VARCHAR(255) DEFAULT '',
    is_foil SMALLINT DEFAULT 0,
    char_type SMALLINT DEFAULT 1,
    clan SMALLINT NOT NULL,
    tribe_name VARCHAR(255) DEFAULT '-',
    skill VARCHAR(255) NOT NULL,
    skill_condition VARCHAR(255) NOT NULL,
    skill_target VARCHAR(255) DEFAULT 'none',
    skill_option VARCHAR(255) DEFAULT 'none,none',
    skill_preprocess VARCHAR(255) DEFAULT 'none,none',
    skill_disc TEXT DEFAULT '',
    org_skill_disc TEXT DEFAULT '',
    evo_skill_disc TEXT DEFAULT '',
    org_evo_skill_disc TEXT DEFAULT '',
    cost smallint NOT NULL,
    atk smallint NOT NULL,
    life smallint NOT NULL,
    evo_atk smallint DEFAULT 0,
    evo_life smallint DEFAULT 0,
    rarity smallint DEFAULT 1,
    get_red_ether integer DEFAULT 0,
    use_red_ether integer DEFAULT 0,
    description text DEFAULT '',
    evo_description text DEFAULT '',
    cv varchar(255) DEFAULT '',
    copyright varchar(50),
    base_card_id integer NOT NULL,
    normal_card_id integer NOT NULL,
    format_type smallint DEFAULT 0,
    restricted_count smallint DEFAULT 3
);